name: Combined Workflow

on: [push, pull_request]

jobs:
  auto-pr:
    uses: Linkdlab/common_workflows/.github/workflows/auto-pr-test-to-dev.yml@main

  python-tests:
    uses: Linkdlab/common_workflows/.github/workflows/py_test.yml@main
